import { useEffect, useState, type CSSProperties } from "react";
import { Waitlist } from "./Waitlist";
import { SectionPickerDemo } from "./SectionPickerDemo";
import { CopyDemo } from "./CopyDemo";
import { ThemeToggle } from "./ThemeToggle";
import { useSmoothScroll } from "@/lib/useSmoothScroll";
import { LAUNCH, annualMonthly, annualSavings } from "@/config/launch";
function Arrow() { return <span aria-hidden="true">↗</span>; }
function Mark() { return <svg viewBox="0 0 36 44" aria-hidden="true"><path d="M18 1 35 10 18 20 1 11Z" fill="currentColor"/><path d="m1 11 17 9v12L1 22Z" fill="currentColor" opacity=".48"/><path d="m18 22 17 10-17 11L1 33Z" fill="currentColor"/></svg>; }
function Brand() { return <a className="brand" href="#top" aria-label="IntoSquare home"><Mark/><span>IntoSquare</span></a>; }
function SectionIntro({title,body}:{title:string;body?:string}) { return <div className="section-intro reveal"><h2>{title}</h2>{body && <p>{body}</p>}</div>; }
function SampleSite({editable=false,mobile=false}:{editable?:boolean;mobile?:boolean}) {
 return <div className={`sample-site ${editable?"editable":""} ${mobile?"mobile-sample":""}`}><div className="sample-nav"><b>forma®</b><span>Spaces for living <Arrow/></span></div><div className="sample-content"><div><span className="sample-kicker">LESS, BUT BETTER.</span><div className="sample-title" data-block="Text">Room to<br/>be yourself.</div><p>Considered spaces.<br/>Everyday possibilities.</p><span className="sample-button" data-block="Button">Explore our spaces <Arrow/></span></div><div className="sample-art" data-block="Image placeholder"><div className="arch"/><div className="pedestal"/><div className="orb"/><span>01 — A little room to imagine.</span></div></div><div className="sample-foot"><span>Thoughtfully designed.</span><span>Made for real life.</span><span>Always yours.</span></div></div>;
}
function IntroVideo() {
 return <figure className="intro-video motion-scene" aria-label="Intro video placeholder. Video coming soon."><div className="video-topline"><span>Figma</span><span className="video-path">Your design <span>→</span> Your website</span><span>Squarespace <Arrow/></span></div><div className="video-canvas"><div className="video-window window-left"><div className="window-bar"><span>Design / Home</span><span>100%</span></div><SampleSite/></div><div className="transfer-trail" aria-hidden="true"><i/><i/><i/></div><div className="transfer-badge"><Mark/></div><div className="video-window window-right"><div className="window-bar"><span>Squarespace / Edit</span><span className="tiny-status">Editable</span></div><SampleSite editable/></div></div><figcaption><span className="play-placeholder" aria-hidden="true">▶</span><div><strong>See your design make the move.</strong><span>Intro video · Coming soon</span></div><span className="video-duration">FIGMA → SQUARESPACE</span></figcaption></figure>;
}
function EditDemo() {
 const [color,setColor]=useState("#d8dccd");
 return <div className="edit-demo" style={{"--sample-bg":color} as CSSProperties}><div className="demo-toolbar"><span><i/> Squarespace editor</span><span>Native blocks</span></div><SampleSite editable/><div className="edit-controls"><span>Try a new background</span><div role="group" aria-label="Preview background color">{["#d8dccd","#ead5bf","#d5deee"].map((c,i)=><button key={c} aria-label={["Sage","Sand","Blue"][i]} aria-pressed={color===c} onClick={()=>setColor(c)} style={{background:c}}/>)}</div></div></div>;
}
function MobileDemo() {
 const [mobile,setMobile]=useState(false);
 return <div className="responsive-demo"><div className="device-switch" role="group" aria-label="Layout preview"><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobile</button></div><div className={`device-preview ${mobile?"is-mobile":""}`}><SampleSite mobile={mobile}/></div><div className="visual-caption">{mobile?"Less space. A layout that follows.":"Your layout, ready for the next screen."}</div></div>;
}
function StyleDemo() {
 const [theme,setTheme]=useState(0);
 const palettes=[["#f9f8f4","#e9e8e2","#58192f","#a78a7f","#201c20"],["#f7f8f4","#d8dccd","#50735d","#a3ac8f","#202c25"]];
 return <div className="style-demo motion-scene"><div className="style-panel"><div className="style-panel-title"><Mark/><span>Site Styles</span><span className="pro-label">PRO</span></div><div className="style-row"><span>Heading 1</span><b>TikTok Sans · 64</b></div><div className="style-row"><span>Paragraph</span><b>TikTok Sans · 18</b></div><div className="palette-swatches">{palettes[theme].map(c=><span key={c} style={{background:c}}/>)}</div><span className="style-status">✓ Typography & palette mapped</span></div><div className="style-result" style={{background:palettes[theme][1],color:palettes[theme][4]}}><span>A LOOK THAT’S YOURS</span><b>Make it<br/>feel like you.</b><span className="style-result-button" style={{background:palettes[theme][2]}}>Let’s begin <Arrow/></span></div><button className="text-button" onClick={()=>setTheme(1-theme)}>Try another palette <span aria-hidden="true">↻</span></button></div>;
}
const questions=[
 ["What do I need to use IntoSquare?","Figma, Chrome, and a Squarespace 7.1 site using Fluid Engine. IntoSquare has two companions: a Figma plugin to copy your design and a Chrome extension to bring it into Squarespace."],
 ["Can I still edit everything in Squarespace?","Supported elements become native Squarespace blocks. Edit text, move blocks, change spacing, and keep building in the normal editor. Unsupported details are flagged before export so you can adjust your design."],
 ["What happens to my images?","The current version creates image placeholders with the layout in place. Add the final images through Squarespace after import. Automatic image upload is not included yet."],
 ["How does the mobile layout work?","Auto Layout can become responsive Squarespace Stacks, with smaller mobile gaps and padding. If your desktop and mobile frames have different grouping or layer order, use Separate blocks to preserve the two arrangements."],
 ["Can I bring my fonts and colors too?","Yes, with Pro. Copy typography and a five-color palette from Figma into native Squarespace Site Styles. Review changes before applying them across your site. Font availability can affect the result."],
 ["What happens if I stop paying?","Your imported content stays in Squarespace and remains editable. The subscription controls future imports and Pro features; it does not lock the pages you already created."],
];
function Pricing() {
 const [annual,setAnnual]=useState(true);
 return <section className="section pricing" id="pricing"><SectionIntro title="Start with your own design." body="Try the workflow for free. Go Pro when you’re ready for more."/><div className="billing-toggle" role="group" aria-label="Billing period"><button aria-pressed={!annual} onClick={()=>setAnnual(false)}>Monthly</button><button aria-pressed={annual} onClick={()=>setAnnual(true)}>Yearly <span>Save {annualSavings}%</span></button></div><div className="price-grid"><article className="price-card reveal"><div className="plan-top"><h3>Free</h3><span>Meet your new workflow.</span></div><div className="price">$0</div><p className="price-detail">No credit card needed.</p><a href="#notify" className="button button-outline">Get notified <Arrow/></a><ul><li>{LAUNCH.freeTransfers} successful transfers{LAUNCH.freeMonthly?" per month":" to try it out"}</li><li>1 Squarespace site</li><li>Figma plugin + Chrome extension</li><li>Desktop and mobile layouts</li><li>Editable native blocks</li></ul></article><article className="price-card price-pro reveal"><div className="plan-top"><h3>Pro</h3><span>For your next project. And the next.</span></div><div className="price">${annual?annualMonthly:LAUNCH.monthly}<span>/ month</span></div><p className="price-detail">{annual?`$${LAUNCH.annual} billed yearly. Save $${LAUNCH.monthly*12-LAUNCH.annual} a year.`:`$${LAUNCH.monthly} billed monthly.`}</p><a href="#notify" className="button">Get notified <Arrow/></a><ul><li>Unlimited transfers</li><li>Unlimited Squarespace sites</li><li>Everything in Free</li><li>Typography & color palette transfer</li><li>Your imported content stays yours</li></ul></article></div><p className="pricing-note">Planned launch pricing in USD. Subscriptions open in October. No payment today.</p></section>;
}
export function Promo() {
 useSmoothScroll();
 const [menu,setMenu]=useState(false);
 useEffect(()=>{
  const elements=document.querySelectorAll(".reveal");
  if (!window.IntersectionObserver || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}}),{threshold:.08});
  elements.forEach(el=>{el.classList.add("will-reveal");observer.observe(el);});
  const scenes=document.querySelectorAll(".motion-scene");
  const motionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("is-in-view",entry.isIntersecting)),{threshold:0});
  scenes.forEach(scene=>motionObserver.observe(scene));
  return ()=>{observer.disconnect();motionObserver.disconnect();};
 },[]);
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header" id="top"><Brand/><button className="menu-toggle" aria-label={menu?"Close menu":"Open menu"} aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?"Close":"Menu"}</button><nav id="main-nav" className={menu?"open":""} aria-label="Main navigation" onClick={()=>setMenu(false)}><a href="#how-it-works">How it works</a><a href="#features">What moves</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div className="header-actions"><ThemeToggle/><a href="#notify" className="button header-cta">Get notified <Arrow/></a></div></header>
 <main id="main"><section className="hero page-width"><div className="launch-pill"><span/> Launching {LAUNCH.month} {LAUNCH.year}</div><h1 id="headline">From Figma to Squarespace.<br/><span>Still your design.</span></h1><div className="hero-bottom"><p>Bring your layouts and site styles into Squarespace.<br className="desktop-br"/> Keep them editable. Keep creating.</p><a className="button" href="#notify">Let me know at launch <Arrow/></a></div><IntroVideo/><div className="hero-proof"><span>Native Squarespace blocks</span><span>Desktop + mobile</span><span>No code to write</span></div></section>
 <section className="section page-width" id="how-it-works"><SectionIntro title="Design. Copy. Keep going." body="A Figma plugin and a Chrome extension, working together."/><div className="steps"><article className="reveal"><SectionPickerDemo/><h3>Pick your section.</h3><p>Select a prepared frame. IntoSquare checks it and points you to any layers that need attention.</p></article><article className="reveal"><CopyDemo logo={<Mark/>}/><h3>Copy it once.</h3><p>Copy from the Figma plugin. Open IntoSquare in Chrome and choose “Paste from Figma.”</p></article><article className="reveal"><CopyDemo transfer/><h3>Paste it into your site.</h3><p>Choose an empty section and transfer. Your design becomes native blocks, ready to edit.</p></article></div></section>
 <section className="section features-section" id="features"><div className="page-width"><SectionIntro title="The design moves. You stay in control."/><article className="feature-wide reveal"><div className="feature-copy"><h3>The handoff is<br/>just the beginning.</h3><p>Text stays text. Buttons stay buttons. Auto Layout becomes Stacks. Change the details right inside Squarespace.</p><div className="block-tags"><span>Text</span><span>Button</span><span>Shape</span><span>Stack</span><span>Line</span></div></div><EditDemo/></article><div className="feature-pair"><article className="feature-card reveal"><div className="feature-copy"><h3>Big ideas.<br/>Smaller screens.</h3><p>Bring responsive Stacks, or transfer separate desktop and mobile layouts as individual blocks.</p></div><MobileDemo/></article><article className="feature-card reveal"><div className="feature-copy"><h3>Bring the look<br/>along, too.</h3><p>Move your typography and five-color palette into real Squarespace Site Styles.</p></div><StyleDemo/></article></div><div className="honest-note"><span>Good to know</span><p>Images arrive as placeholders. Different desktop and mobile arrangements use Separate blocks. IntoSquare flags unsupported details before you export.</p><a href="#faq">A few more answers <Arrow/></a></div></div></section>
 <div className="page-width"><Pricing/><section className="section faq reveal" id="faq"><div><h2>Glad you asked.</h2><p>Something else on your mind?<br/><a href="mailto:hello@intosquare.app">Say hello <Arrow/></a></p></div><div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section><Waitlist/></div></main><footer className="site-footer page-width"><div className="footer-main"><Brand/><p>Less rebuilding. More creating.</p><a href="mailto:hello@intosquare.app">Get support <Arrow/></a><a href="https://www.instagram.com/intosquare.app/" target="_blank" rel="noopener noreferrer">Instagram <Arrow/></a></div><div className="footer-bottom"><span>© 2026 IntoSquare</span><span>Independently made. Not affiliated with Figma or Squarespace.</span><a href="#notify">Launch updates <Arrow/></a></div></footer></>;
}
